### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by FartyPants** [theovercomer8/captionr#3] opened 2023-02-12 07:05 UTC
it is looking for the pkl in one folder up, not the project
File "G:\captionr\captionr\clip_interrogator.py", line 76, in load_clip_model
    with open(os.path.join(config.cache_path,'ViT-H-14_laion2b_s32b_b79k_flavors.pkl'), 'wb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\data\\ViT-H-14_laion2b_s32b_b79k_flavors.pkl'

looking in G:\\data\
should be looking in G:\captionr\data\

**Comment by theovercomer8** [comment] 2023-02-12 13:10
On it, thanks for the report.

**Comment by theovercomer8** [comment] 2023-02-12 13:17
Can you get latest and verify the issue is corrected?

**Comment by theovercomer8** [comment] 2023-02-12 16:43
Marking as closed

**Closed by theovercomer8** 2023-02-12 16:43 UTC
